### ISSUE TITLE
CrudController:: denyAccessUnlessGranted overriding final method

### ISSUE THREAD

**Issue by n3r0-ch** [whatwedo/CrudBundle#38]
Method `CrudController:: denyAccessUnlessGranted` is overriding final method `Symfony\Bundle\FrameworkBundle\Controller\AbstractController::denyAccessUnlessGranted()`.  `Symfony\Bundle\FrameworkBundle\Controller\AbstractController::denyAccessUnlessGranted()` will crash if CrudBundle is used with disabled firewall authentication.  

@lukasluecke @xarem do you have any idea how to implement this beautifully?

**Comment by lukasluecke** [comment]
I propose ignoring this for now, since we basically only call the parent method. The method is not in fact final, but only marked as final in a PHPDoc as a way to discourage overriding it. Chances are that the issue we solve by overriding it (skipping the access checks if there is no user token) will have a clean solution before they actually enforce the finality on the method signature.
