### ISSUE TITLE
Export-File Title

### ISSUE THREAD

**Issue by rugbymauri** [whatwedo/CrudBundle#82]
the filename of the xslx-export should have, the entity name and timestamp.

<entity-title>-<yyyy-mm-dd_hh:ss>.xlsx

**Comment by QuanTumli** [comment]
As there exists an international standard for date/time related data (ISO 8601, https://en.wikipedia.org/wiki/ISO_8601) I would use their convention.

So
- `YYYY-MM-DD` for date
- `Thh:mm:ss` for time

Some examples:

- `<Entity1>_2022-03-31T18:30:19.xlsx`
- `<Entity2>_2021-11-26T09:36:41.xlsx`

**Comment by xarem** [comment]
please use the entity title instead of the entity name, because most of our users only know the translated name of an entity (f.ex. "Anlässe" instead of "occasion"). With the [Slugger](https://symfony.com/doc/current/components/string.html#slugger) of the String Component we can create safe filenames from the titles (`Anlaesse_2021-11-26T09:36:41.xlsx`).

**Comment by tuxes3** [comment]
`:` is an illegal file name character. We chose this as default:
```php
        $prefix = $this->translator->trans(static::getEntityTitlePlural());
        $suffix = date('Y-m-d\TH_i_s');
        return sprintf('%s_%s.xlsx', $prefix, $suffix);
```
